apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.containerPort }}