apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate 
metadata:
  name: {{ .Values.certificate.name }} 
  namespace: {{ .Values.certificate.namespace }} 
spec:
  acme:
    config:
    - dns01:
        provider: {{ .Values.certificate.dnsProvider }} 
      domains:
      - {{ .Values.certificate.domains }} 
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
  - {{ .Values.certificate.dnsNames }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.issuerRef.name }}
  secretName: {{ .Values.issuerRef.secretName }}