apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }} 
  namespace: {{ .Values.namespace }} 
spec:
  acme:
    server: {{ .Values.letsencrypt.Url }} 
    email: {{ .Values.email }} 
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    dns01:
      providers:
      - name: {{ .Values.dnsProvider }} 
        route53:
          accessKeyID: {{ .Values.awsAccessKeyID }}
          region: {{ .Values.awsRegion }}
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: {{ .Values.secretAccessKeySecretRef.name }}