# Default values for byor-voting-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: mongo
namespace: byor-ns
image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 27017
service:
  type: containerPort
  port: 27017
  targetPort: 27017