version: 2.1
only_tagged: &only_tagged
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/
commands:
  add_missing_dependencies:
    steps:
      - run:
          name: Add curl, git, make and aws-cli
          command: |
            apt-get update
            apt-get install -y curl git make jq curl python3-pip
            pip3 install awscli --upgrade
      - run:
          name: Install Docker client
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            rm -Rf get-docker.sh
            docker --version
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version
  run_common_initial_steps:
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
          # Inactive for now... needs to be whitelisted (and/or OS), see https://circleci.com/docs/2.0/docker-layer-caching/
          docker_layer_caching: true
      - add_missing_dependencies
      - checkout
defaults: &defaults
  docker:
    - image: ubuntu:18.04
jobs:
  deploy:
    <<: *defaults
    steps:
      - run_common_initial_steps
      - run:
          name: Deploy VotingApp for integration tests
          command: aws/deploy_to_lambda.sh circleci
  test:
    <<: *defaults
    steps:
      - run_common_initial_steps
      - run:
          name: Execute E2E tests
          command: echo "TODO: E2E tests"
  deliver:
    <<: *defaults
    steps:
      - run_common_initial_steps
      - run:
          name: Deploy VotingApp to production
          command: echo "TODO: aws/deploy_to_lambda.sh"
workflows:
  version: 2.1
  tagged:
    jobs:
      - deploy:
          <<: *only_tagged
          context: BYOR-VotingApp
      - test:
          <<: *only_tagged
          context: BYOR-VotingApp
          requires:
            - deploy
      - deliver:
          <<: *only_tagged
          context: BYOR-VotingApp
          requires:
            - test

