apiVersion: v1
entries:
  byor-voting-chart:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-06-13T17:29:26.937954+02:00
    description: Byor-VotingChart helm chart
    digest: b6efdc5302a4f5be932ad2518a3f7cc7af0931d8763cfddf584cc9d9ba9e5a50
    name: byor-voting-chart
    urls:
    - byor-voting-chart-0.1.0.tgz
    version: 0.1.0
generated: 2019-06-13T17:29:26.937162+02:00
