apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory  # Production URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory #Staging URL
    email: r.senthilreddy@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    dns01:
      providers:
      - name: aws-route53
        route53:
          accessKeyID: ""
          region: eu-west-1
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key    
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: byor-gateway-certs
  namespace: istio-system
spec:
  acme:
    config:
    - dns01:
        provider: aws-route53
      domains:
      - "byor.martjanplanet.com"
  commonName: "byor.martjanplanet.com"
  dnsNames:
  - "byor.martjanplanet.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: istio-ingressgateway-certs
